/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestaoveiculos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class PainelMain extends javax.swing.JFrame {
      public char tipo;
    /**
     * Creates new form PainelMain
     */
    public PainelMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_Modelo = new javax.swing.ButtonGroup();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAnoFabricacao = new javax.swing.JTextField();
        lblTipoCombustivel = new javax.swing.JLabel();
        txtTipoCombustivel = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        rdoCarro = new javax.swing.JRadioButton();
        rdoMoto = new javax.swing.JRadioButton();
        lblNumPortas = new javax.swing.JLabel();
        txtNumPortas = new javax.swing.JTextField();
        lblCapPortaMalas = new javax.swing.JLabel();
        txtCapPortaMalas = new javax.swing.JTextField();
        lblCilindradas = new javax.swing.JLabel();
        txtCilindradas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTransmissao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCalculaImposto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblModelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModelo.setText("Modelo:");

        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMarca.setText("Marca:");

        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Ano de Fabricação:");

        txtAnoFabricacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblTipoCombustivel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipoCombustivel.setText("Tipo de Combustível:");

        txtTipoCombustivel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlaca.setText("Placa:");

        txtPlaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnGroup_Modelo.add(rdoCarro);
        rdoCarro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoCarro.setText("Carro");

        btnGroup_Modelo.add(rdoMoto);
        rdoMoto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMoto.setText("Moto");

        lblNumPortas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumPortas.setText("Número de portas:");

        txtNumPortas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblCapPortaMalas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCapPortaMalas.setText("Capacidade do porta-malas:");

        txtCapPortaMalas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblCilindradas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCilindradas.setText("Cilindradas:");

        txtCilindradas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tipo de Transmissão:");

        txtTransmissao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCalculaImposto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalculaImposto.setText("Calcular Imposto");
        btnCalculaImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaImpostoActionPerformed(evt);
            }
        });

        tblDados.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Modelo", "Marca", "Ano Fabricação", "Tipo Combustível", "Placa"
            }
        ));
        jScrollPane1.setViewportView(tblDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblModelo)
                                .addComponent(lblMarca))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                .addComponent(txtMarca)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTipoCombustivel)
                            .addGap(18, 18, 18)
                            .addComponent(txtTipoCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCilindradas)
                                .addGap(18, 18, 18)
                                .addComponent(txtCilindradas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCapPortaMalas)
                                .addGap(18, 18, 18)
                                .addComponent(txtCapPortaMalas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumPortas)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumPortas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoCarro)
                                .addGap(18, 18, 18)
                                .addComponent(rdoMoto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlaca)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlaca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(btnSalvar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalculaImposto)
                                    .addComponent(txtTransmissao))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCombustivel)
                    .addComponent(txtTipoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCarro)
                    .addComponent(rdoMoto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPortas)
                    .addComponent(txtNumPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapPortaMalas)
                    .addComponent(txtCapPortaMalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCilindradas)
                            .addComponent(txtCilindradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTransmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnCalculaImposto)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(rdoCarro.isSelected()){
            tipo = 'C';
        }

        else if(rdoMoto.isSelected()){
            tipo = 'M';
        }
        
        Carro c = new Carro(tipo, txtModelo.getText(),txtMarca.getText(),txtAnoFabricacao.getText(),txtTipoCombustivel.getText(),txtPlaca.getText());
        Moto m = new Moto(tipo, txtModelo.getText(),txtMarca.getText(),txtAnoFabricacao.getText(),txtTipoCombustivel.getText(),txtPlaca.getText());
        
        DefaultTableModel tabela = (DefaultTableModel) tblDados.getModel();
        tabela.addRow(c.obterDados());
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCalculaImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaImpostoActionPerformed
        if(rdoCarro.isSelected()) {
            JOptionPane.showMessageDialog(null, "Imposto para carro: R$10000,00 + adicional por porta!","Alerta!", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if(rdoMoto.isSelected()) {
            JOptionPane.showMessageDialog(null, "Imposto para moto: R$5000,00 + adicional por cilindrada!","Alerta!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculaImpostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculaImposto;
    private javax.swing.ButtonGroup btnGroup_Modelo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapPortaMalas;
    private javax.swing.JLabel lblCilindradas;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumPortas;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTipoCombustivel;
    private javax.swing.JRadioButton rdoCarro;
    private javax.swing.JRadioButton rdoMoto;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtAnoFabricacao;
    private javax.swing.JTextField txtCapPortaMalas;
    private javax.swing.JTextField txtCilindradas;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumPortas;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTipoCombustivel;
    private javax.swing.JTextField txtTransmissao;
    // End of variables declaration//GEN-END:variables
}
