package conexao;

import DAO.alunoDAO;
import DAO.professorDAO;
import beans.Aluno;
import beans.Professor;
import javax.swing.JOptionPane;

public class InterfaceConsultaEscola extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceConsultaEscola
     */
    public InterfaceConsultaEscola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpIdentificador = new javax.swing.ButtonGroup();
        btnGrpConsultaIdentificador = new javax.swing.ButtonGroup();
        lblDisciplina = new javax.swing.JLabel();
        rdoAluno = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtDisciplina = new javax.swing.JTextField();
        rdoProfessor = new javax.swing.JRadioButton();
        lblIdentificador = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblIDconsulta = new javax.swing.JLabel();
        txtIDconsulta = new javax.swing.JTextField();
        rdoConsultaAluno = new javax.swing.JRadioButton();
        rdoConsultaProfessor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDisciplina.setText("Disciplina:");

        btnGrpIdentificador.add(rdoAluno);
        rdoAluno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoAluno.setText("Aluno (a)");
        rdoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAlunoActionPerformed(evt);
            }
        });

        btnGrpIdentificador.add(rdoProfessor);
        rdoProfessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoProfessor.setText("Professor (a)");
        rdoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoProfessorActionPerformed(evt);
            }
        });

        lblIdentificador.setText("Identificador:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdade.setText("Idade:");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurso.setText("Curso:");

        btnConsultar.setBackground(new java.awt.Color(60, 63, 65));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(60, 63, 65));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 255, 0));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(60, 63, 65));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 51, 51));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID.setText("ID:");

        lblIDconsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIDconsulta.setText("ID:");

        txtIDconsulta.setEditable(false);

        btnGrpConsultaIdentificador.add(rdoConsultaAluno);
        rdoConsultaAluno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoConsultaAluno.setText("Aluno (a)");
        rdoConsultaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoConsultaAlunoActionPerformed(evt);
            }
        });

        btnGrpConsultaIdentificador.add(rdoConsultaProfessor);
        rdoConsultaProfessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoConsultaProfessor.setText("Professor (a)");
        rdoConsultaProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoConsultaProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDisciplina)
                                    .addComponent(lblCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCurso)
                                    .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnAtualizar)
                                .addGap(36, 36, 36)
                                .addComponent(btnExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdentificador)
                                .addGap(18, 18, 18)
                                .addComponent(rdoAluno)
                                .addGap(18, 18, 18)
                                .addComponent(rdoProfessor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblIdade))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome)
                                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIDconsulta)
                                .addGap(18, 18, 18)
                                .addComponent(txtIDconsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(rdoConsultaAluno)
                        .addGap(18, 18, 18)
                        .addComponent(rdoConsultaProfessor)
                        .addGap(26, 26, 26)
                        .addComponent(btnConsultar)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoConsultaAluno)
                        .addComponent(rdoConsultaProfessor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblID)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDconsulta)
                    .addComponent(txtIDconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoAluno)
                    .addComponent(rdoProfessor)
                    .addComponent(lblIdentificador))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplina)
                    .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAlunoActionPerformed

        if(rdoAluno.isSelected()){
            txtCurso.setVisible(true);
            txtDisciplina.setVisible(false);
        }

    }//GEN-LAST:event_rdoAlunoActionPerformed

    private void rdoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoProfessorActionPerformed
        if(rdoProfessor.isSelected()){
            txtDisciplina.setVisible(true);
            txtCurso.setVisible(false);
        }
    }//GEN-LAST:event_rdoProfessorActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        if(rdoConsultaAluno.isSelected()){
            Aluno a = new Aluno();
            a.setId(Integer.parseInt(txtID.getText()));
            a.setNome(txtNome.getText());
            a.setIdade(Integer.parseInt(txtIdade.getText()));
            rdoAluno.setSelected(true);
            a.setCurso(txtCurso.getText());
           

            alunoDAO aDAO = new alunoDAO();
            aDAO.atualizar(a);

            limparFormulario();
        }
        else if(rdoConsultaProfessor.isSelected()){
            Professor p = new Professor();
            p.setId(Integer.parseInt(txtID.getText()));
            p.setNome(txtNome.getText());
            p.setIdade(Integer.parseInt(txtIdade.getText()));
            rdoProfessor.setSelected(true);
            p.setDisciplina(txtDisciplina.getText());
           

            professorDAO pDAO = new professorDAO();
            pDAO.atualizar(p);

            limparFormulario();
        }
        
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       
        if(rdoConsultaAluno.isSelected()){
            alunoDAO aDAO = new alunoDAO();
            int id = Integer.parseInt(txtID.getText());

            Aluno a = aDAO.consulta(id);

            if(a == null){
                limparFormulario();
                JOptionPane.showMessageDialog(this, "Aluno(a) não encontrado(a)");
            }
            else{
                txtIDconsulta.setText(String.valueOf(a.getId()));
                txtNome.setText(a.getNome());
                txtIdade.setText(String.valueOf(a.getIdade()));

                rdoAluno.setSelected(true);

                txtCurso.setText(a.getCurso());
                txtDisciplina.setVisible(false);
                txtCurso.setVisible(true);
                }   
            
        }
        else if (rdoConsultaProfessor.isSelected()){
            professorDAO pDAO = new professorDAO();
            int id = Integer.parseInt(txtID.getText());

            Professor p = pDAO.consulta(id);

            if(p == null){
                limparFormulario();
                JOptionPane.showMessageDialog(this, "Professor(a) não encontrado(a)");
            }
            else{
                txtIDconsulta.setText(String.valueOf(p.getId()));
                txtNome.setText(p.getNome());
                txtIdade.setText(String.valueOf(p.getIdade()));

                rdoProfessor.setSelected(true);

                txtDisciplina.setText(p.getDisciplina());
                txtDisciplina.setVisible(true);
                txtCurso.setVisible(false);

                }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void rdoConsultaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoConsultaAlunoActionPerformed
        if(rdoConsultaAluno.isSelected()){
            limparFormularioMenosID();
            rdoAluno.setSelected(true);
            txtDisciplina.setVisible(false);
            txtCurso.setVisible(true);
        }
        
    }//GEN-LAST:event_rdoConsultaAlunoActionPerformed

    private void rdoConsultaProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoConsultaProfessorActionPerformed
        if(rdoConsultaProfessor.isSelected()){
            limparFormularioMenosID();
            rdoProfessor.setSelected(true);
            txtDisciplina.setVisible(true);
            txtCurso.setVisible(false);
        }
        
    }//GEN-LAST:event_rdoConsultaProfessorActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        if(rdoConsultaAluno.isSelected()){
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este(a) aluno(a)?", "Exclusão", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){

                alunoDAO aDAO = new alunoDAO();
                aDAO.excluir(Integer.parseInt(txtID.getText()));
                limparFormulario();

            }
        }
        else if(rdoConsultaProfessor.isSelected()){
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este(a) professor(a) ?", "Exclusão", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){

                professorDAO pDAO = new professorDAO();
                pDAO.excluir(Integer.parseInt(txtID.getText()));
                limparFormulario();

            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void limparFormulario(){
        txtID.setText("");
        txtIDconsulta.setText("");
        txtNome.setText("");
        btnGrpIdentificador.clearSelection();
        txtIdade.setText("");
        txtIdade.setText("");
        txtCurso.setText("");
        txtDisciplina.setText("");
    }
    
    private void limparFormularioMenosID(){
        txtIDconsulta.setText("");
        txtNome.setText("");
        btnGrpIdentificador.clearSelection();
        txtIdade.setText("");
        txtIdade.setText("");
        txtCurso.setText("");
        txtDisciplina.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultaEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultaEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultaEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultaEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceConsultaEscola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup btnGrpConsultaIdentificador;
    private javax.swing.ButtonGroup btnGrpIdentificador;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDconsulta;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblNome;
    private javax.swing.JRadioButton rdoAluno;
    private javax.swing.JRadioButton rdoConsultaAluno;
    private javax.swing.JRadioButton rdoConsultaProfessor;
    private javax.swing.JRadioButton rdoProfessor;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtDisciplina;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDconsulta;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
