package conexao;

import DAO.alunoDAO;
import DAO.professorDAO;
import beans.Aluno;
import beans.Professor;

public class InterfaceCadastroEscola extends javax.swing.JFrame {

    String identificador;
    
    /**
     * Creates new form InterfaceCadastroEscola
     */
    public InterfaceCadastroEscola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGrpIdentificador = new javax.swing.ButtonGroup();
        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblDisciplina = new javax.swing.JLabel();
        rdoAluno = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtDisciplina = new javax.swing.JTextField();
        rdoProfessor = new javax.swing.JRadioButton();
        lblIdentificador = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdade.setText("Idade:");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurso.setText("Curso:");

        lblDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDisciplina.setText("Disciplina:");

        rdoGrpIdentificador.add(rdoAluno);
        rdoAluno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoAluno.setText("Aluno (a)");
        rdoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAlunoActionPerformed(evt);
            }
        });

        rdoGrpIdentificador.add(rdoProfessor);
        rdoProfessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoProfessor.setText("Professor (a)");
        rdoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoProfessorActionPerformed(evt);
            }
        });

        lblIdentificador.setText("Identificador:");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdentificador)
                                .addGap(18, 18, 18)
                                .addComponent(rdoAluno)
                                .addGap(18, 18, 18)
                                .addComponent(rdoProfessor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDisciplina)
                                    .addComponent(lblCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(txtDisciplina))))
                        .addContainerGap(360, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblIdade))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txtIdade))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoAluno)
                    .addComponent(rdoProfessor)
                    .addComponent(lblIdentificador))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplina)
                    .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnCadastrar)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAlunoActionPerformed
        
        if(rdoAluno.isSelected()){
            txtCurso.setVisible(true);
            txtDisciplina.setVisible(false);         
        }
        
    }//GEN-LAST:event_rdoAlunoActionPerformed

    private void rdoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoProfessorActionPerformed
       if(rdoProfessor.isSelected()){
            txtDisciplina.setVisible(true); 
            txtCurso.setVisible(false);                
        }
    }//GEN-LAST:event_rdoProfessorActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        Conexao c = new Conexao();
        c.getConexao();
        
        if(rdoAluno.isSelected()){
            
            identificador = "Aluno";
            String nome = txtNome.getText();
            int idade = Integer.parseInt(txtIdade.getText());
            String curso = txtCurso.getText();
            
            Aluno a = new Aluno(nome, idade, curso);
            
            a.setNome(nome);
            a.setIdade(idade);
            a.setCurso(curso);
            
            
            alunoDAO aDAO = new alunoDAO();
            aDAO.inserir(a);
        }
        else if(rdoProfessor.isSelected()){
            
            identificador = "Professor";
            String nome = txtNome.getText();
            int idade = Integer.parseInt(txtIdade.getText());
            String disciplina = txtDisciplina.getText();
            
            Professor p = new Professor(nome, idade, disciplina);
            
            p.setNome(nome);
            p.setIdade(idade);
            p.setDisciplina(disciplina);
           
            
            professorDAO pDAO = new professorDAO();
            pDAO.inserir(p);
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadastroEscola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblNome;
    private javax.swing.JRadioButton rdoAluno;
    private javax.swing.ButtonGroup rdoGrpIdentificador;
    private javax.swing.JRadioButton rdoProfessor;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtDisciplina;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
